apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-redis-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration-redis-mongo
  template:
    metadata:
      labels:        
        app: expiration-redis-mongo
    spec:
      containers:
        - name: expiration-redis-mongo
          image: redis
---
apiVersion: v1
kind: Service
metadata:
  name: expiration-redis-srv
spec:
  selector:
    app: expiration-redis
  ports:
    - name: db
      protocol: TCP
      port: 6379
      targetPort: 6379                   