name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'
  
jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - uses: azure/aks-set-context@v1
        with:
            creds: '${{ secrets.AZURE_CREDENTIALS }}'
            resource-group: 'Ticketing'
            cluster-name: 'TicketingCluster'
        id: login
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
