name: deploy-payments

on:
  push:
    branches:
      - master
    paths:
      - 'payments/**'
  
jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && docker build -t elavagni/payments .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push elavagni/payments
      - uses: azure/aks-set-context@v1
        with:
            creds: '${{ secrets.AZURE_CREDENTIALS }}'
            resource-group: 'Ticketing'
            cluster-name: 'TicketingCluster'
        id: login
      - run: kubectl rollout restart deployment payments-depl
