name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'
  
jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t elavagni/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push elavagni/auth
      - uses: azure/aks-set-context@v1
        with:
            creds: '${{ secrets.AZURE_CREDENTIALS }}'
            resource-group: 'Ticketing'
            cluster-name: 'TicketingCluster'
        id: login
      - uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            infra/k8s/auth-depl.yml    
